from ._ASRService import *
from ._AnimationService import *
from ._FaceDetector import *
from ._FaceDetectorService import *
from ._Rest import *
from ._TabletService import *
from ._Text2Speech import *
from ._VoiceDetectionService import *
from ._WakeUp import *
