// Generated by gencpp from file features/AnimationService.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_ANIMATIONSERVICE_H
#define FEATURES_MESSAGE_ANIMATIONSERVICE_H

#include <ros/service_traits.h>


#include <features/AnimationServiceRequest.h>
#include <features/AnimationServiceResponse.h>


namespace features
{

struct AnimationService
{

typedef AnimationServiceRequest Request;
typedef AnimationServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnimationService
} // namespace features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::features::AnimationService > {
  static const char* value()
  {
    return "d8b7e9905e6a815639dc67959117aa3b";
  }

  static const char* value(const ::features::AnimationService&) { return value(); }
};

template<>
struct DataType< ::features::AnimationService > {
  static const char* value()
  {
    return "features/AnimationService";
  }

  static const char* value(const ::features::AnimationService&) { return value(); }
};


// service_traits::MD5Sum< ::features::AnimationServiceRequest> should match
// service_traits::MD5Sum< ::features::AnimationService >
template<>
struct MD5Sum< ::features::AnimationServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::features::AnimationService >::value();
  }
  static const char* value(const ::features::AnimationServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::AnimationServiceRequest> should match
// service_traits::DataType< ::features::AnimationService >
template<>
struct DataType< ::features::AnimationServiceRequest>
{
  static const char* value()
  {
    return DataType< ::features::AnimationService >::value();
  }
  static const char* value(const ::features::AnimationServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::features::AnimationServiceResponse> should match
// service_traits::MD5Sum< ::features::AnimationService >
template<>
struct MD5Sum< ::features::AnimationServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::features::AnimationService >::value();
  }
  static const char* value(const ::features::AnimationServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::AnimationServiceResponse> should match
// service_traits::DataType< ::features::AnimationService >
template<>
struct DataType< ::features::AnimationServiceResponse>
{
  static const char* value()
  {
    return DataType< ::features::AnimationService >::value();
  }
  static const char* value(const ::features::AnimationServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEATURES_MESSAGE_ANIMATIONSERVICE_H
