// Generated by gencpp from file features/ASRServiceResponse.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_ASRSERVICERESPONSE_H
#define FEATURES_MESSAGE_ASRSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace features
{
template <class ContainerAllocator>
struct ASRServiceResponse_
{
  typedef ASRServiceResponse_<ContainerAllocator> Type;

  ASRServiceResponse_()
    : output()  {
    }
  ASRServiceResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::features::ASRServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::features::ASRServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ASRServiceResponse_

typedef ::features::ASRServiceResponse_<std::allocator<void> > ASRServiceResponse;

typedef boost::shared_ptr< ::features::ASRServiceResponse > ASRServiceResponsePtr;
typedef boost::shared_ptr< ::features::ASRServiceResponse const> ASRServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::features::ASRServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::features::ASRServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::features::ASRServiceResponse_<ContainerAllocator1> & lhs, const ::features::ASRServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::features::ASRServiceResponse_<ContainerAllocator1> & lhs, const ::features::ASRServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace features

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::features::ASRServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::features::ASRServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::ASRServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::ASRServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::ASRServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::ASRServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::features::ASRServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87e4b3ab48eadee8169367653b22c9a8";
  }

  static const char* value(const ::features::ASRServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87e4b3ab48eadee8ULL;
  static const uint64_t static_value2 = 0x169367653b22c9a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::features::ASRServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "features/ASRServiceResponse";
  }

  static const char* value(const ::features::ASRServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::features::ASRServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String output\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::features::ASRServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::features::ASRServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ASRServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::features::ASRServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::features::ASRServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEATURES_MESSAGE_ASRSERVICERESPONSE_H
