// Generated by gencpp from file features/FaceDetectorService.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_FACEDETECTORSERVICE_H
#define FEATURES_MESSAGE_FACEDETECTORSERVICE_H

#include <ros/service_traits.h>


#include <features/FaceDetectorServiceRequest.h>
#include <features/FaceDetectorServiceResponse.h>


namespace features
{

struct FaceDetectorService
{

typedef FaceDetectorServiceRequest Request;
typedef FaceDetectorServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceDetectorService
} // namespace features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::features::FaceDetectorService > {
  static const char* value()
  {
    return "c02e001e41cea4c43b2f6bd8b43a538c";
  }

  static const char* value(const ::features::FaceDetectorService&) { return value(); }
};

template<>
struct DataType< ::features::FaceDetectorService > {
  static const char* value()
  {
    return "features/FaceDetectorService";
  }

  static const char* value(const ::features::FaceDetectorService&) { return value(); }
};


// service_traits::MD5Sum< ::features::FaceDetectorServiceRequest> should match
// service_traits::MD5Sum< ::features::FaceDetectorService >
template<>
struct MD5Sum< ::features::FaceDetectorServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::features::FaceDetectorService >::value();
  }
  static const char* value(const ::features::FaceDetectorServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::FaceDetectorServiceRequest> should match
// service_traits::DataType< ::features::FaceDetectorService >
template<>
struct DataType< ::features::FaceDetectorServiceRequest>
{
  static const char* value()
  {
    return DataType< ::features::FaceDetectorService >::value();
  }
  static const char* value(const ::features::FaceDetectorServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::features::FaceDetectorServiceResponse> should match
// service_traits::MD5Sum< ::features::FaceDetectorService >
template<>
struct MD5Sum< ::features::FaceDetectorServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::features::FaceDetectorService >::value();
  }
  static const char* value(const ::features::FaceDetectorServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::FaceDetectorServiceResponse> should match
// service_traits::DataType< ::features::FaceDetectorService >
template<>
struct DataType< ::features::FaceDetectorServiceResponse>
{
  static const char* value()
  {
    return DataType< ::features::FaceDetectorService >::value();
  }
  static const char* value(const ::features::FaceDetectorServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEATURES_MESSAGE_FACEDETECTORSERVICE_H
