// Generated by gencpp from file features/FaceDetectorServiceRequest.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_FACEDETECTORSERVICEREQUEST_H
#define FEATURES_MESSAGE_FACEDETECTORSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace features
{
template <class ContainerAllocator>
struct FaceDetectorServiceRequest_
{
  typedef FaceDetectorServiceRequest_<ContainerAllocator> Type;

  FaceDetectorServiceRequest_()
    {
    }
  FaceDetectorServiceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::features::FaceDetectorServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::features::FaceDetectorServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetectorServiceRequest_

typedef ::features::FaceDetectorServiceRequest_<std::allocator<void> > FaceDetectorServiceRequest;

typedef boost::shared_ptr< ::features::FaceDetectorServiceRequest > FaceDetectorServiceRequestPtr;
typedef boost::shared_ptr< ::features::FaceDetectorServiceRequest const> FaceDetectorServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::features::FaceDetectorServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace features

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::features::FaceDetectorServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::FaceDetectorServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::FaceDetectorServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::features::FaceDetectorServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "features/FaceDetectorServiceRequest";
  }

  static const char* value(const ::features::FaceDetectorServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::features::FaceDetectorServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetectorServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::features::FaceDetectorServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::features::FaceDetectorServiceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FEATURES_MESSAGE_FACEDETECTORSERVICEREQUEST_H
