// Generated by gencpp from file features/FaceDetectorServiceResponse.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_FACEDETECTORSERVICERESPONSE_H
#define FEATURES_MESSAGE_FACEDETECTORSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace features
{
template <class ContainerAllocator>
struct FaceDetectorServiceResponse_
{
  typedef FaceDetectorServiceResponse_<ContainerAllocator> Type;

  FaceDetectorServiceResponse_()
    : presence()  {
    }
  FaceDetectorServiceResponse_(const ContainerAllocator& _alloc)
    : presence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _presence_type;
  _presence_type presence;





  typedef boost::shared_ptr< ::features::FaceDetectorServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::features::FaceDetectorServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetectorServiceResponse_

typedef ::features::FaceDetectorServiceResponse_<std::allocator<void> > FaceDetectorServiceResponse;

typedef boost::shared_ptr< ::features::FaceDetectorServiceResponse > FaceDetectorServiceResponsePtr;
typedef boost::shared_ptr< ::features::FaceDetectorServiceResponse const> FaceDetectorServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::features::FaceDetectorServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::features::FaceDetectorServiceResponse_<ContainerAllocator1> & lhs, const ::features::FaceDetectorServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.presence == rhs.presence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::features::FaceDetectorServiceResponse_<ContainerAllocator1> & lhs, const ::features::FaceDetectorServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace features

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::features::FaceDetectorServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::FaceDetectorServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::FaceDetectorServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c02e001e41cea4c43b2f6bd8b43a538c";
  }

  static const char* value(const ::features::FaceDetectorServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc02e001e41cea4c4ULL;
  static const uint64_t static_value2 = 0x3b2f6bd8b43a538cULL;
};

template<class ContainerAllocator>
struct DataType< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "features/FaceDetectorServiceResponse";
  }

  static const char* value(const ::features::FaceDetectorServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool presence\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::features::FaceDetectorServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.presence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetectorServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::features::FaceDetectorServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::features::FaceDetectorServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "presence: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.presence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEATURES_MESSAGE_FACEDETECTORSERVICERESPONSE_H
