// Generated by gencpp from file features/FaceDetector.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_FACEDETECTOR_H
#define FEATURES_MESSAGE_FACEDETECTOR_H

#include <ros/service_traits.h>


#include <features/FaceDetectorRequest.h>
#include <features/FaceDetectorResponse.h>


namespace features
{

struct FaceDetector
{

typedef FaceDetectorRequest Request;
typedef FaceDetectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceDetector
} // namespace features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::features::FaceDetector > {
  static const char* value()
  {
    return "c02e001e41cea4c43b2f6bd8b43a538c";
  }

  static const char* value(const ::features::FaceDetector&) { return value(); }
};

template<>
struct DataType< ::features::FaceDetector > {
  static const char* value()
  {
    return "features/FaceDetector";
  }

  static const char* value(const ::features::FaceDetector&) { return value(); }
};


// service_traits::MD5Sum< ::features::FaceDetectorRequest> should match
// service_traits::MD5Sum< ::features::FaceDetector >
template<>
struct MD5Sum< ::features::FaceDetectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::features::FaceDetector >::value();
  }
  static const char* value(const ::features::FaceDetectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::FaceDetectorRequest> should match
// service_traits::DataType< ::features::FaceDetector >
template<>
struct DataType< ::features::FaceDetectorRequest>
{
  static const char* value()
  {
    return DataType< ::features::FaceDetector >::value();
  }
  static const char* value(const ::features::FaceDetectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::features::FaceDetectorResponse> should match
// service_traits::MD5Sum< ::features::FaceDetector >
template<>
struct MD5Sum< ::features::FaceDetectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::features::FaceDetector >::value();
  }
  static const char* value(const ::features::FaceDetectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::FaceDetectorResponse> should match
// service_traits::DataType< ::features::FaceDetector >
template<>
struct DataType< ::features::FaceDetectorResponse>
{
  static const char* value()
  {
    return DataType< ::features::FaceDetector >::value();
  }
  static const char* value(const ::features::FaceDetectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEATURES_MESSAGE_FACEDETECTOR_H
