// Generated by gencpp from file features/TabletServiceResponse.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_TABLETSERVICERESPONSE_H
#define FEATURES_MESSAGE_TABLETSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace features
{
template <class ContainerAllocator>
struct TabletServiceResponse_
{
  typedef TabletServiceResponse_<ContainerAllocator> Type;

  TabletServiceResponse_()
    : ack()  {
    }
  TabletServiceResponse_(const ContainerAllocator& _alloc)
    : ack(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::features::TabletServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::features::TabletServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TabletServiceResponse_

typedef ::features::TabletServiceResponse_<std::allocator<void> > TabletServiceResponse;

typedef boost::shared_ptr< ::features::TabletServiceResponse > TabletServiceResponsePtr;
typedef boost::shared_ptr< ::features::TabletServiceResponse const> TabletServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::features::TabletServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::features::TabletServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::features::TabletServiceResponse_<ContainerAllocator1> & lhs, const ::features::TabletServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::features::TabletServiceResponse_<ContainerAllocator1> & lhs, const ::features::TabletServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace features

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::features::TabletServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::features::TabletServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::TabletServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::TabletServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::TabletServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::TabletServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::features::TabletServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92dac20d0566a4f591e3ecd6dcd3458b";
  }

  static const char* value(const ::features::TabletServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92dac20d0566a4f5ULL;
  static const uint64_t static_value2 = 0x91e3ecd6dcd3458bULL;
};

template<class ContainerAllocator>
struct DataType< ::features::TabletServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "features/TabletServiceResponse";
  }

  static const char* value(const ::features::TabletServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::features::TabletServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String ack\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::features::TabletServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::features::TabletServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TabletServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::features::TabletServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::features::TabletServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEATURES_MESSAGE_TABLETSERVICERESPONSE_H
