// Generated by gencpp from file features/TabletServiceRequest.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_TABLETSERVICEREQUEST_H
#define FEATURES_MESSAGE_TABLETSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace features
{
template <class ContainerAllocator>
struct TabletServiceRequest_
{
  typedef TabletServiceRequest_<ContainerAllocator> Type;

  TabletServiceRequest_()
    : input()  {
    }
  TabletServiceRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::features::TabletServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::features::TabletServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TabletServiceRequest_

typedef ::features::TabletServiceRequest_<std::allocator<void> > TabletServiceRequest;

typedef boost::shared_ptr< ::features::TabletServiceRequest > TabletServiceRequestPtr;
typedef boost::shared_ptr< ::features::TabletServiceRequest const> TabletServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::features::TabletServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::features::TabletServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::features::TabletServiceRequest_<ContainerAllocator1> & lhs, const ::features::TabletServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::features::TabletServiceRequest_<ContainerAllocator1> & lhs, const ::features::TabletServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace features

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::features::TabletServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::features::TabletServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::TabletServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::TabletServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::TabletServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::TabletServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::features::TabletServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53159356b214209e01f9f93bea8428fd";
  }

  static const char* value(const ::features::TabletServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53159356b214209eULL;
  static const uint64_t static_value2 = 0x01f9f93bea8428fdULL;
};

template<class ContainerAllocator>
struct DataType< ::features::TabletServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "features/TabletServiceRequest";
  }

  static const char* value(const ::features::TabletServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::features::TabletServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String input\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::features::TabletServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::features::TabletServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TabletServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::features::TabletServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::features::TabletServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEATURES_MESSAGE_TABLETSERVICEREQUEST_H
