// Generated by gencpp from file features/Text2Speech.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_TEXT2SPEECH_H
#define FEATURES_MESSAGE_TEXT2SPEECH_H

#include <ros/service_traits.h>


#include <features/Text2SpeechRequest.h>
#include <features/Text2SpeechResponse.h>


namespace features
{

struct Text2Speech
{

typedef Text2SpeechRequest Request;
typedef Text2SpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Text2Speech
} // namespace features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::features::Text2Speech > {
  static const char* value()
  {
    return "8b55dba5ce52d0e4d2c88f751b201113";
  }

  static const char* value(const ::features::Text2Speech&) { return value(); }
};

template<>
struct DataType< ::features::Text2Speech > {
  static const char* value()
  {
    return "features/Text2Speech";
  }

  static const char* value(const ::features::Text2Speech&) { return value(); }
};


// service_traits::MD5Sum< ::features::Text2SpeechRequest> should match
// service_traits::MD5Sum< ::features::Text2Speech >
template<>
struct MD5Sum< ::features::Text2SpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::features::Text2Speech >::value();
  }
  static const char* value(const ::features::Text2SpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::Text2SpeechRequest> should match
// service_traits::DataType< ::features::Text2Speech >
template<>
struct DataType< ::features::Text2SpeechRequest>
{
  static const char* value()
  {
    return DataType< ::features::Text2Speech >::value();
  }
  static const char* value(const ::features::Text2SpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::features::Text2SpeechResponse> should match
// service_traits::MD5Sum< ::features::Text2Speech >
template<>
struct MD5Sum< ::features::Text2SpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::features::Text2Speech >::value();
  }
  static const char* value(const ::features::Text2SpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::Text2SpeechResponse> should match
// service_traits::DataType< ::features::Text2Speech >
template<>
struct DataType< ::features::Text2SpeechResponse>
{
  static const char* value()
  {
    return DataType< ::features::Text2Speech >::value();
  }
  static const char* value(const ::features::Text2SpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEATURES_MESSAGE_TEXT2SPEECH_H
