// Generated by gencpp from file features/VoiceDetectionService.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_VOICEDETECTIONSERVICE_H
#define FEATURES_MESSAGE_VOICEDETECTIONSERVICE_H

#include <ros/service_traits.h>


#include <features/VoiceDetectionServiceRequest.h>
#include <features/VoiceDetectionServiceResponse.h>


namespace features
{

struct VoiceDetectionService
{

typedef VoiceDetectionServiceRequest Request;
typedef VoiceDetectionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoiceDetectionService
} // namespace features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::features::VoiceDetectionService > {
  static const char* value()
  {
    return "c4e176c9f8ad32507aa931a67656b59c";
  }

  static const char* value(const ::features::VoiceDetectionService&) { return value(); }
};

template<>
struct DataType< ::features::VoiceDetectionService > {
  static const char* value()
  {
    return "features/VoiceDetectionService";
  }

  static const char* value(const ::features::VoiceDetectionService&) { return value(); }
};


// service_traits::MD5Sum< ::features::VoiceDetectionServiceRequest> should match
// service_traits::MD5Sum< ::features::VoiceDetectionService >
template<>
struct MD5Sum< ::features::VoiceDetectionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::features::VoiceDetectionService >::value();
  }
  static const char* value(const ::features::VoiceDetectionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::VoiceDetectionServiceRequest> should match
// service_traits::DataType< ::features::VoiceDetectionService >
template<>
struct DataType< ::features::VoiceDetectionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::features::VoiceDetectionService >::value();
  }
  static const char* value(const ::features::VoiceDetectionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::features::VoiceDetectionServiceResponse> should match
// service_traits::MD5Sum< ::features::VoiceDetectionService >
template<>
struct MD5Sum< ::features::VoiceDetectionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::features::VoiceDetectionService >::value();
  }
  static const char* value(const ::features::VoiceDetectionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::features::VoiceDetectionServiceResponse> should match
// service_traits::DataType< ::features::VoiceDetectionService >
template<>
struct DataType< ::features::VoiceDetectionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::features::VoiceDetectionService >::value();
  }
  static const char* value(const ::features::VoiceDetectionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEATURES_MESSAGE_VOICEDETECTIONSERVICE_H
