// Generated by gencpp from file features/VoiceDetectionServiceResponse.msg
// DO NOT EDIT!


#ifndef FEATURES_MESSAGE_VOICEDETECTIONSERVICERESPONSE_H
#define FEATURES_MESSAGE_VOICEDETECTIONSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int16MultiArray.h>

namespace features
{
template <class ContainerAllocator>
struct VoiceDetectionServiceResponse_
{
  typedef VoiceDetectionServiceResponse_<ContainerAllocator> Type;

  VoiceDetectionServiceResponse_()
    : output()  {
    }
  VoiceDetectionServiceResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int16MultiArray_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VoiceDetectionServiceResponse_

typedef ::features::VoiceDetectionServiceResponse_<std::allocator<void> > VoiceDetectionServiceResponse;

typedef boost::shared_ptr< ::features::VoiceDetectionServiceResponse > VoiceDetectionServiceResponsePtr;
typedef boost::shared_ptr< ::features::VoiceDetectionServiceResponse const> VoiceDetectionServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::features::VoiceDetectionServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::features::VoiceDetectionServiceResponse_<ContainerAllocator1> & lhs, const ::features::VoiceDetectionServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::features::VoiceDetectionServiceResponse_<ContainerAllocator1> & lhs, const ::features::VoiceDetectionServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace features

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4e176c9f8ad32507aa931a67656b59c";
  }

  static const char* value(const ::features::VoiceDetectionServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4e176c9f8ad3250ULL;
  static const uint64_t static_value2 = 0x7aa931a67656b59cULL;
};

template<class ContainerAllocator>
struct DataType< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "features/VoiceDetectionServiceResponse";
  }

  static const char* value(const ::features::VoiceDetectionServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int16MultiArray output\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int16MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int16[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::features::VoiceDetectionServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VoiceDetectionServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::features::VoiceDetectionServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::features::VoiceDetectionServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::std_msgs::Int16MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEATURES_MESSAGE_VOICEDETECTIONSERVICERESPONSE_H
